language: php

php:
    - 7.2
    - 7.3
    - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - touch .env

script: vendor/bin/phpunit

after_success:
    - travis_retry php vendor/bin/php-coveralls
