#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

if (!defined('BASE_DIR')) {
    define('BASE_DIR', __DIR__);
}
if (!defined('CONTENT_PATH')) {
    define('CONTENT_PATH', 'content/');
}

$app = new Application();
$kernel = new Statico\Core\Kernel;
$kernel->bootstrap();
$container = $kernel->getContainer();
$app->add($container->get('Statico\Core\Console\Shell'));
$app->add($container->get('Statico\Core\Console\Server'));
$app->run();
