#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php';

use Symfony\Component\Console\Application;

$app = new Application();
$kernel = new Statico\Core\Kernel;
$kernel->bootstrap();
$container = $kernel->getContainer();
$app->add($container->get('Statico\Core\Console\Shell'));
$app->add($container->get('Statico\Core\Console\Server'));
$app->add($container->get('Statico\Core\Console\GenerateIndex'));
$app->add($container->get('Statico\Core\Console\GenerateSitemap'));
$app->run();
