forms:
  contact:
    elements:
      - spec:
          name: name
          options:
            label: Your name
          type: Text
      - spec:
          name: submit
          options:
            label: submit
          type: Submit
