forms:
  contact:
    attributes:
      class: form-inline my-2 my-lg-0 pull-right
    elements:
      - spec:
          name: name
          options:
            label: Your name
          type: Text
          attributes:
            class: form-control mr-sm-2 m-2 p-2 border border-solid border-gray-400
      - spec:
          name: email
          options:
            label: Your email address
          type: Email
          attributes:
            class: form-control mr-sm-2 m-2 p-2 border border-solid border-gray-400
      - spec:
          name: message
          options:
            label: Your message
          type: Textarea
          attributes:
            class: form-control mr-sm-2 m-2 p-2 border border-solid border-gray-400
      - spec:
          name: submit
          type: submit
          attributes:
            class: form-control mr-sm-2 m-2 p-2 bg-white text-purple hover:bg-purple hover:text-white border border-solid border-purple hover:border-transparent rounded
            value: "Submit"
