forms:
  contact:
    attributes:
      class: form-inline my-2 my-lg-0 pull-right
    elements:
      - spec:
          name: name
          options:
            label: Your name
          type: Text
          attributes:
            class: form-control mr-sm-2
      - spec:
          name: submit
          type: submit
          attributes:
            class: form-control mr-sm-2
            value: "Submit"
